baseURL: 'https://www.svorstol.com'
languageCode: en-US
theme: hugo-bearcub
title: Stein-Otto Svorstøl

params:
  author:
    name: Stein-Otto Svorstøl
    email: stein-otto@svorstol.com
  goatcounterID: svorstol

ignoreLogs: ['warning-goldmark-raw-html']
